const express = require("express");
const settingsController = require("../controllers/settingsController");
const { authenticate, allowRoles } = require("../middleware/auth");
const mailAccountController = require("../controllers/mailAccountController");
const userController = require("../controllers/userController");

const router = express.Router();
router.use(authenticate);
router.get("/users", allowRoles("admin"), userController.getUsers);
router.post("/users", allowRoles("admin"), userController.createUser);
router.patch("/users/:id/role", allowRoles("admin"), userController.updateUserRole);
router.delete("/users/:id", allowRoles("admin"), userController.deleteUser);
router.get("/admin-access", allowRoles("admin"), userController.getAdminAccess);
router.put("/admin-access/rebind", allowRoles("admin"), userController.rebindAdminAccess);
router.get("/mail-account", mailAccountController.getMailAccount);
router.get("/shared-mail-accounts", mailAccountController.getSharedMailAccounts);
router.post("/shared-mail-accounts", allowRoles("admin"), mailAccountController.saveSharedMailAccount);
router.post("/shared-mail-accounts/:id/test", allowRoles("admin"), mailAccountController.testSharedMailAccount);
router.put("/shared-mail-accounts/:id/primary", allowRoles("admin"), mailAccountController.setPrimarySharedMailAccount);
router.delete("/shared-mail-accounts/:id", allowRoles("admin"), mailAccountController.deleteSharedMailAccount);
router.put("/mail-account", mailAccountController.saveMailAccount);
router.post("/mail-account/test", mailAccountController.testMailAccount);
router.delete("/mail-account", mailAccountController.deleteMailAccount);
router.get("/approval-workflow", settingsController.getApprovalWorkflow);
router.put("/approval-workflow", allowRoles("admin"), settingsController.updateApprovalWorkflow);
router.get("/storage", allowRoles("admin"), settingsController.getStorageStats);
router.get("/storage/cleanup-preview", allowRoles("admin"), settingsController.previewMailCleanup);
router.post("/storage/cleanup", allowRoles("admin"), settingsController.cleanupOldMails);
router.get("/health", allowRoles("admin"), settingsController.getHealth);
router.get("/backups", allowRoles("admin"), settingsController.listBackups);
router.get("/backups/:id/preview", allowRoles("admin"), settingsController.previewBackup);
router.get("/backups/:id/attachments/:storedName", allowRoles("admin"), settingsController.downloadBackupAttachment);
router.post("/backups/path/test", allowRoles("admin"), settingsController.testBackupPath);
router.put("/backups/path", allowRoles("admin"), settingsController.updateBackupPath);
router.put("/backups/schedule", allowRoles("admin"), settingsController.updateBackupSchedule);
router.post("/backups", allowRoles("admin"), settingsController.createBackup);
router.post("/backups/:id/restore", allowRoles("admin"), settingsController.restoreBackup);
router.get("/storage/temporary-uploads", allowRoles("admin"), settingsController.previewTemporaryUploadCleanup);
router.post("/storage/temporary-uploads/cleanup", allowRoles("admin"), settingsController.cleanupTemporaryUploads);

module.exports = router;
